mainapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'mainapp'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^search/$', views.search,name='search'),
]

twitmap/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^googlemaps/',include('mainapp.urls')),
    url(r'^admin/', admin.site.urls),
]

mainapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Filter(models.Model):
    filter_condition_User=models.CharField(max_length=200)
    filter_condition_Key_Word=models.CharField(max_length=200)
    filter_condition_Hashtag=models.CharField(max_length=200)
    filter_condition_markerCoord=models.CharField(max_length=200)
    submit_time=models.DateTimeField('date published')
    submitter = models.CharField(max_length=200)
    def __str__(self):
    	return 'submitter: '+self.submitter+' time: '+str(self.submit_time)+' User: '+self.filter_condition_User+' Keyword: '+self.filter_condition_Key_Word+' Hashtags: '+self.filter_condition_Hashtag+' markerCoord: '+self.filter_condition_markerCoord

mainapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.views import generic
from .models import Filter
from django.urls import reverse
from django.template import loader
# Create your views here.
import inspect
from datetime import datetime
from elasticsearch import Elasticsearch
import json
from django.utils.safestring import mark_safe

from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream
import random

#Variables that contains the user credentials to access Twitter API 
access_token = ""
access_token_secret = ""
consumer_key = ""
consumer_secret = ""



def index(request,results=None,markerCoord=None):
    att=inspect.getmembers(Filter, lambda a:not(inspect.isroutine(a)))
    att=[a[1] for a in att if a[0]=='__dict__'][0]
    attribute_list=[a[len('filter_condition_'):] for a in att if a.startswith('filter_condition_')]
    context_object_name = 'attribute_list'
    template=loader.get_template('mainapp/index.html')
    if results==None:
    	results=[]
    if markerCoord==None:
    	markerCoord=[]
    else:
        markerCoord=str(markerCoord).strip('()')
        markerCoord=markerCoord.split(',')
        markerCoord=[float(l) for l in markerCoord]
    print 'mc=',markerCoord,type(markerCoord)
    try:
        results=json.dumps(results,sort_keys=True, indent=4)
    except:None
    #print results
    context={
    'attribute_list':attribute_list,
    'results':mark_safe(results),
    'markerCoord':mark_safe(markerCoord),
    }
    return HttpResponse(template.render(context, request))	
    
def search(request):
    l = StdOutListener()
    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    stream = Stream(auth, l,timeout=1.5)

    mapping ="Key_word"
    host='https://search-twitmap-cupqelpnpd3niqdiaprtmmfo7m.us-east-1.es.amazonaws.com'
    es = Elasticsearch([host])
    postForm=request.POST
    search_request={}
    for i in postForm:
        if not (i=='csrfmiddlewaretoken'):
            search_request[i]=postForm[i]
            print i,search_request[i]
    filter=Filter(filter_condition_User=search_request['User'], filter_condition_Hashtag=search_request['Hashtag'],filter_condition_Key_Word=search_request['Key_Word'],submit_time=datetime.now(),submitter=request.META['CSRF_COOKIE'],filter_condition_markerCoord=search_request['markerCoord'])
    print filter
    print 
    mc=filter.filter_condition_markerCoord
    searchBox=mc.strip("()")
    searchBox=searchBox.split(',')
    searchBox=[float(i) for i in searchBox]
    boxSize=1
    searchBox=[searchBox[1]-boxSize,searchBox[0]-boxSize,searchBox[1]+boxSize,searchBox[0]+boxSize]
    print searchBox
    doc = {
        "query": {
            "bool":{
                "should":[
                    {"query_string": {
                        "fields":["user.screen_name","user.name"],
                        "query" : "*"+filter.filter_condition_User+"*" if len(filter.filter_condition_User) else ''
                        }
                    },
                    {"query_string": {
                        "fields":["entities.hashtags.text"],
                        "query" : "*"+str(filter.filter_condition_Hashtag)+"*" if len(str(filter.filter_condition_Hashtag)) else ''
                        }
                    },
                    {"query_string": {
                        "fields":["text"],
                        "query" : "*"+filter.filter_condition_Key_Word+"*" if len(filter.filter_condition_Key_Word) else ''
                        }
                   }
                ]
            }       
        }
    }

    res = es.search(index="tweets", doc_type='tweet', body=doc)
    f=open('log.log','a')
    print >>f, '-------------------Search reuqestion at %s---------------------\n' % str(filter.submit_time)
    global tweets
    tweets=[]
    try:
        stream.filter(locations=searchBox)
    except:
    	None
#    print len(tweets)
    tweets=[json.loads(tweet) for tweet in tweets]
#    for tweet in tweets:
#        print json.dumps(tweet,sort_keys=True, indent=4)

    results=[]
    for hit in tweets:
    	tweet={}
        try:
            tweet["User"]=hit['user']['screen_name']+', '+hit['user']['name']
            tweet["Location"]=hit['user']['location']
            ht={}
            for i in hit['entities']['hashtags']:
            	ht.add(i["text"])
            tweet["Hashtags"]=ht
            tweet["Text"]=hit['text']
            try: 
            	bb=hit['place']['bounding_box']['coordinates'][0]
            	r=random.random()
                lat=(bb[0][0]+bb[1][0]+bb[2][0]+bb[3][0])/len(bb)+(r-0.5)*0.00001
                r=random.random()
                lng=(bb[0][1]+bb[1][1]+bb[2][1]+bb[3][1])/len(bb)+(r-0.5)*0.00001
            except:
            	print 'lat error'
            tweet["Coord"]=str(lat)+','+str(lng)
        except:
        	#print 'info error'
        	None
        filter.save()
       	results.append(tweet)
    f.close()
    return index(request,results,mc)



class StdOutListener(StreamListener):    
    def on_data(self, data):
        tweets.append(data)
        return True
    
    def on_error(self, status):
        print(status)

mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<h2 style="text-align: center;"><strong><span style="color: #0000ff;">TwitterMap</span></strong></h2>
<p style="text-align: center;">by Guangkun Li(gl1546@nyu.edu) and Chenyu Xu(cx463@nyu.edu)</p>
<p style="text-align: left;">1. Drag or single click the marker to change the coordinates</p>
<p style="text-align: left;">2. Please click on the "submit" button to start search nearby tweets of the marker location</p>

<html>
<head>
<style>
.dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}

.dropbtn:hover, .dropbtn:focus {
    background-color: #3e8e41;
}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 220px;
    overflow: auto;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown a:hover {background-color: #f1f1f1}

.show {display:block;}
</style>
</head>
<body>


<div class="dropdown">
<button onclick="myFunction()" class="dropbtn">Filter</button>
  <div id="myDropdown" class="dropdown-content">
    <form id = "ddform" action="{% url 'mainapp:search' %}" method="post">
    	{% csrf_token %}
      <style> 
      input[type="submit"] {
      display:block;
      margin: 0 auto;
	}

	</style>

	<br>
	{% if attribute_list %}
    	{% for item in attribute_list %}
    		{%if item != "markerCoord"  %}
    			&nbsp&nbsp{{item}}:<br>
    			&nbsp&nbsp&nbsp&nbsp<input type="text" name={{item}}><br><br>
    		{% else %}
	    		&nbsp&nbspMarker Coordinate:<br>
    			&nbsp&nbsp&nbsp&nbsp<input type="text" name={{item}}><br><br>
			{% endif %}
    	{% endfor %}
	{% endif %}
	  <br>


	 <input align="middle" type="submit" value="Submit">
	</form>
  </div>
 
</div>

<script>
/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}


</script>

</body>
</html>

	

<!DOCTYPE html>
<html>
  <head>
    <style>
       #map {
        height: 600px;
        width: 100%;
       }
    </style>
  </head>
  <body>
  	<div id="map"></div>


    <script>
    var map;
    var marker;
    var infowindow;
    var arrayTweets=[];
      function initMap() {
        var mouse = {lat: -25.363, lng: 131.044};
        var tweets={{results}};
        var image='http://maps.google.com/mapfiles/dir_60.png';
 
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5,
          center: mouse,
        });
        marker = new google.maps.Marker({
          position: mouse,
          map: map,
          draggable: true,
				});
		oFormObject = document.forms['ddform'];

   
       google.maps.event.addListener(map, 'click', function(event) {
          mouse = event.latLng;
          marker.setPosition(mouse);
          console.log(marker.getPosition().toString());
          oFormObject.elements["markerCoord"].value ==marker.getPosition().toString();
        });

       google.maps.event.addListener(marker, 'drag', function(event) {
          console.log(marker.getPosition().toString());
          oFormObject.elements["markerCoord"].value=marker.getPosition().toString();
        });

		window.onload = function() {
       //when the document is finished loading, replace everything
       //between the <a ...> </a> tags with the value of splitText
		var mc={{markerCoord}};		
        console.log('mc',mc[0],mc[1]);
        if (mc.length>0){
        	marker.setPosition({
        		lat:mc[0],
        		lng:mc[1],
        	})
        map.setCenter(marker.getPosition());
		oFormObject.elements["markerCoord"].value=marker.getPosition().toString();

                for (i=0;i<tweets.length;i++){
        	var loc;
        	try{
        	  if (tweets[i]["Coord"].length>0){
          	  var arr=tweets[i]["Coord"].split(',');
        		loc= {
         	     lat: parseFloat(arr[1]),
        	      lng: parseFloat(arr[0]),
       	     };
        	console.log(loc);

        	}}
        	catch (err){
        		loc={
        			lat:marker.getPosition().lat(),
        			lng:marker.getPosition().lng(),

        		};
        	console.log(loc);

        	}
            var str=JSON.stringify(tweets[i]);
			var tweet=new google.maps.Marker({
          	position: loc,
          	map: map,
          	icon: image,
          	title: str,
				});

			google.maps.event.addListener(tweet, "click", function() {
  		    	if (infowindow) {infowindow.close();}
  		    	var content=this.getTitle();
  				content=JSON.parse(content);
  				var contentString=''

  				for (key in content){
					var kvStr=''
  					if (content[key] !='[object Object]'){
					kvStr=key+": "+content[key];
					}
					else{kvStr=key+": None";}
  					console.log(kvStr);
  					contentString=contentString+kvStr+'<br>';
  				}
    		  	infowindow = new google.maps.InfoWindow({content: contentString });
  				infowindow.open(map, this);
		});
        }
        }
        else{
          if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            map.setCenter(pos);
            marker.setPosition(pos);
	        oFormObject.elements["markerCoord"].value=marker.getPosition().toString();


          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }


        }
        console.log(marker.getPosition().lat(),marker.getPosition().lng());
} 

      }
    </script>
    
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=GOOGLE_MAPS_API_KEY&callback=initMap">
    </script>
  </body>
</html>